

replicaCount: 1

image:
  repository: fayizv/python-flask
  pullPolicy: IfNotPresent
  tag: ""

imagePullSecrets: []
nameOverride: "helm-app"
fullnameOverride: "helm-chart"

serviceAccount:             
  create: true
  annotations: {}
  name: "helm-app"
       

service:
  type: LoadBalancer
  port: 5000

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []


resources: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
